# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8c6e122efc51e7ee8c7711052ffa8469f50fea8cef74ebc1e7dc489efcfe4c237e7b615954bd40ce5a502fe5413ff38eced8f397f8fae215991c59ac4c093b8

test:
  secret_key_base: 54170d7c122b7c600a640099eab06fba90c2a6a1b113941582b4e47955690771ed31e117027949343b01dab29c44df242fe700ab6a1b2fad8a39fc1db1f7d574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
